# Generated by Django 4.2.5 on 2023-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=30)),
                ('native', models.CharField(max_length=100)),
                ('cgpa', models.FloatField(max_length=5.2)),
            ],
        ),
    ]
